### ISSUE TITLE
Lỗi ghi dữ liệu NV4.0.23

### ISSUE THREAD

**Issue by daivietpda** [webvangvn/nv4_module_laws#1]
Bác fix cho nv4.0.23 được không ạ 
Bị lỗi khi đăng 1 tài liệu nó không chạy khi click vào "ghi dữ liệu ..."

**Comment by webvangvn** [comment]
để mình test lại trên phiên bản 4.0.23

**Comment by daivietpda** [comment]
Bác test rồi fix nhé 
thank bác trước

**Comment by ductrung** [comment]
sao em cài lên khi chọn file để úp lên nó không hiện để mình chèn, mặc dù mở thư mục upload/laws vẫn có file và khi nhấn ghi dữ liệu không đc

**Comment by lyhuutrong** [comment]
bạn ơi kiểm tra dùm mình sao mình ghi dữ liệu không được ạ ?
mình xài cho nukeviet 4.0.23 ạ

**Comment by ductrung** [comment]
chào bạn, module này đang trong quá trình hoàn thiện bạn ah, có chi bạn cứ
lên diễn đàn trao đổi với anh em

Vào 15:10 Ngày 23 tháng 11 năm 2015, lyhuutrong notifications@github.com
đã viết:

**Comment by lyhuutrong** [comment]
vậy mong sớm có được module văn bản. xin cảm ơn bạn đã trả lời. bữa giờ mình lên diễn đàn mà ko thấy có bạn nào trả lời nên mình mạo mụi lên đây hỏi ạ

**Comment by ductrung** [comment]
không sao bạn ah, mình cũng đang cần nhưng chắc chờ đội code chỉnh lại đã
bạn ah, cho mình xem demo của bạn đc không, có chi anh em mình trao đổi cho
nhau, mình ở đà nẵng, còn bạn ở chỗ nào

Vào 16:21 Ngày 23 tháng 11 năm 2015, lyhuutrong notifications@github.com
đã viết:

**Comment by lyhuutrong** [comment]
mình ở cần thơ bạn ạ.
demo : http://qltt.vn
mình ấn vào ghi dữ liệu mà không được bạn ạ. Nản ghê.
Bạn có yahoo không ductrung ? bạn cho mình xin yahoo được ko ạ ?
Mình đang hoàn thiện website cho Hội đồng nghiệp Quản Lý Thị Trường

**Comment by ductrung** [comment]
lâu lắm rồi không dùng bạn ah, có chi qua gmail bạn nhé

Vào 15:26 Ngày 23 tháng 11 năm 2015, lyhuutrong notifications@github.com
đã viết:

**Comment by webvangvn** [comment]
đã fix lên RC 2
